"""Privacy-gated Cloudflare Pages dashboard publication bundles."""

from __future__ import annotations

from html import escape
from io import BytesIO
import json
import re
from typing import Any
from urllib.parse import urlparse
from zipfile import ZIP_DEFLATED, ZipFile


ALLOWED_WIDGETS = {"kpi", "field_kpi", "chart", "field_chart", "map", "epi_curve", "geo_map", "content"}


def publication_audit(config: Any, dashboard: dict[str, Any], mode: str, upstream_url: str = "") -> dict[str, Any]:
    if mode not in {"snapshot", "live"}: raise ValueError("Publication mode must be snapshot or live.")
    if mode == "live" and (urlparse(upstream_url).scheme != "https" or not urlparse(upstream_url).netloc):
        raise ValueError("Live publication requires an HTTPS aggregate API URL.")
    findings, sources = [], []
    for widget in dashboard.get("widgets", []):
        kind = widget.get("type")
        if kind not in ALLOWED_WIDGETS: findings.append(f"Unsupported widget type: {kind}"); continue
        dataset_name, fields = widget.get("dataset"), []
        if kind in {"field_kpi", "field_chart"}: fields = [widget.get("field")]
        elif kind == "epi_curve": fields = [widget.get("date_field"), widget.get("value_field")]
        elif kind == "geo_map": fields = [widget.get("latitude_field"), widget.get("longitude_field")]
        if dataset_name in config.datasets:
            dataset = config.datasets[dataset_name]
            protected = [name for name in fields if name and name in dataset.fields and dataset.fields[name].protected]
            if protected: findings.append(f"{widget.get('title', kind)} uses protected field(s): {', '.join(protected)}")
            sources.append({"dataset": dataset_name, "fields": [name for name in fields if name], "output": "aggregate"})
        if kind == "kpi" and widget.get("indicator") in config.indicators:
            indicator = config.indicators[widget["indicator"]]
            dataset = config.datasets[indicator.dataset]
            fields = [indicator.field, indicator.numerator, indicator.denominator, indicator.date_field, *indicator.filters]
            protected = [name for name in fields if name and name in dataset.fields and dataset.fields[name].protected]
            if protected: findings.append(f"{widget.get('title', kind)} indicator uses protected field(s): {', '.join(protected)}")
            sources.append({"dataset": indicator.dataset, "indicator": indicator.name, "output": "aggregate"})
        if kind in {"chart", "map"} and widget.get("dimension") in config.dimensions:
            dimension = config.dimensions[widget["dimension"]]; field = config.datasets[dimension.dataset].fields[dimension.field]
            if field.protected: findings.append(f"{widget.get('title', kind)} uses protected dimension field: {dimension.field}")
            sources.append({"dataset": dimension.dataset, "field": dimension.field, "output": "aggregate"})
    return {"approved": not findings, "mode": mode, "dashboard_id": dashboard.get("id") or dashboard.get("name"), "row_level_records": 0, "protected_fields": 0 if not findings else len(findings), "sources": sources, "findings": findings, "live_endpoint": upstream_url if mode == "live" else "", "notice": "Publication exports aggregate dashboard evidence only; this is a technical control, not a legal privacy certification."}


def build_bundle(dashboard: dict[str, Any], snapshot: dict[str, Any], branding: dict[str, Any], mode: str, upstream_url: str = "", refresh_minutes: int = 15) -> bytes:
    refresh = max(1, min(int(refresh_minutes), 1440))
    title = str(dashboard.get("title") or dashboard.get("label") or "Public Health Dashboard")
    payload = json.dumps({"dashboard": dashboard, "snapshot": snapshot, "mode": mode, "refresh_minutes": refresh, "basemap": branding.get("basemap", "carto-light")}).replace("</", "<\\/")
    primary = branding.get("primary_color", "#087e8b")
    html = _interactive_page(title, payload, primary, mode)
    worker = _worker(upstream_url, refresh) if mode == "live" else ""
    readme = f"""# {title}\n\nGenerated by PHFrame.\n\nMode: {mode}\n\nDeploy with `npx wrangler pages deploy . --project-name YOUR_PROJECT`.\n"""
    output = BytesIO()
    with ZipFile(output, "w", ZIP_DEFLATED) as archive:
        archive.writestr("index.html", html); archive.writestr("README.md", readme)
        archive.writestr("_headers", "/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: no-referrer\n  X-Frame-Options: DENY\n")
        if worker: archive.writestr("_worker.js", worker)
    return output.getvalue()


def safe_project_name(value: str) -> str:
    clean = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")[:58]
    if not clean: raise ValueError("Cloudflare project name is required.")
    return clean


def _page(title: str, payload: str, primary: str, mode: str) -> str:
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><style>:root{{--p:{escape(primary)};--bg:#f4f7f7;--card:#fff;--text:#17313d}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--text);font:15px/1.5 system-ui}}header{{padding:2.4rem 5vw;color:#fff;background:var(--p)}}main{{max-width:1200px;margin:auto;padding:2rem}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem}}article{{padding:1.2rem;background:var(--card);border:1px solid #d5e1e3;border-radius:14px}}.value{{font-size:2.5rem;font-weight:800;color:var(--p)}}.bars i{{display:block;height:12px;margin:.4rem 0;background:var(--p);border-radius:9px}}footer{{padding:2rem;text-align:center;color:#64777e}}.status{{font-size:.8rem;opacity:.8}}</style></head><body><header><h1>{escape(title)}</h1><p class="status">{escape(mode.title())} dashboard · aggregate data only</p></header><main><div class="grid" id="dashboard"></div></main><footer>Published with PHFrame</footer><script id="ph-data" type="application/json">{payload}</script><script>const state=JSON.parse(document.querySelector('#ph-data').textContent),host=document.querySelector('#dashboard');function draw(data){{const values=data.widgets||[];host.innerHTML=values.map(w=>`<article><h2>${{esc(w.title||w.type)}}</h2>${{render(w)}}</article>`).join('')}}function esc(v){{const e=document.createElement('span');e.textContent=v??'';return e.innerHTML}}function render(w){{if(w.html)return w.html;if(w.value!==undefined)return `<div class="value">${{Number(w.value).toLocaleString()}}</div><p>${{esc(w.operation||'aggregate')}}</p>`;if(w.values){{const m=Math.max(1,...w.values.map(x=>x.count||x.value||0));return `<div class="bars">${{w.values.slice(0,20).map(x=>`<b>${{esc(x.label||x.value||x.date)}}</b><i style="width:${{Math.max(2,(x.count||x.value||0)/m*100)}}%"></i>`).join('')}}</div>`}}return '<p>No aggregate data available.</p>'}}draw(state.snapshot);async function refresh(){{try{{const r=await fetch('/api/live');if(r.ok)draw(await r.json())}}catch(e){{}}}}if(state.mode==='live'){{refresh();setInterval(refresh,state.refresh_minutes*60000)}}</script></body></html>'''


def _interactive_page(title: str, payload: str, primary: str, mode: str) -> str:
    """Build a portable dashboard, including interactive boundary maps."""
    page = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>__TITLE__</title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>
:root{--p:__PRIMARY__;--bg:#f4f7f7;--card:#fff;--text:#17313d}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.5 system-ui}header{padding:2.4rem 5vw;color:#fff;background:var(--p)}main{max-width:1200px;margin:auto;padding:2rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem}article{padding:1.2rem;background:var(--card);border:1px solid #d5e1e3;border-radius:14px}article.map-card{grid-column:1/-1}.value{font-size:2.5rem;font-weight:800;color:var(--p)}.bars i{display:block;height:12px;margin:.4rem 0;background:var(--p);border-radius:9px}.map{height:480px;border-radius:10px;overflow:hidden}.legend{display:grid;gap:4px;min-width:115px;padding:10px;background:#fffffff0;border-radius:8px;box-shadow:0 2px 12px #0003}.legend span{display:flex;align-items:center;gap:6px;font-size:12px}.legend i{width:14px;height:14px;border:1px solid #789}footer{padding:2rem;text-align:center;color:#64777e}.status{font-size:.8rem;opacity:.8}@media(max-width:640px){main{padding:1rem}.map{height:390px}}
</style></head><body><header><h1>__TITLE__</h1><p class="status">__MODE__ dashboard · aggregate data only</p></header><main><div class="grid" id="dashboard"></div></main><footer>Published with PHFrame</footer><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script id="ph-data" type="application/json">__PAYLOAD__</script><script>
const state=JSON.parse(document.querySelector('#ph-data').textContent),host=document.querySelector('#dashboard'),pendingMaps=[];
const tiles={'openstreetmap':['https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png','© OpenStreetMap contributors'],'carto-light':['https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png','© OpenStreetMap contributors © CARTO'],'carto-dark':['https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png','© OpenStreetMap contributors © CARTO'],'esri-imagery':['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}','Tiles © Esri']};
function esc(v){const e=document.createElement('span');e.textContent=v??'';return e.innerHTML}function norm(v){return String(v||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]/g,'')}
function render(w){if(w.html)return w.html;if(w.geojson){const id=`map-${pendingMaps.length}`;pendingMaps.push({id,w});return `<div class="map" id="${id}"></div>`}if(w.value!==undefined)return `<div class="value">${Number(w.value).toLocaleString()}</div><p>${esc(w.operation||'aggregate')}</p>`;if(w.values){const m=Math.max(1,...w.values.map(x=>x.count||x.value||0));return `<div class="bars">${w.values.slice(0,20).map(x=>`<b>${esc(x.label||x.value||x.date)}</b><i style="width:${Math.max(2,(x.count||x.value||0)/m*100)}%"></i>`).join('')}</div>`}return '<p>No aggregate data available.</p>'}
function draw(data){pendingMaps.length=0;const values=data.widgets||[];host.innerHTML=values.map(w=>`<article class="${w.geojson?'map-card':''}"><h2>${esc(w.title||w.type)}</h2>${render(w)}</article>`).join('');requestAnimationFrame(()=>pendingMaps.forEach(initMap))}
function initMap(item){if(!window.L)return;const w=item.w,counts=new Map((w.values||[]).map(x=>[norm(x.value),Number(x.count||0)])),max=Math.max(1,...counts.values()),color=v=>!v?'#e7ecef':v/max>.8?'#7f0000':v/max>.6?'#c62828':v/max>.4?'#ef5350':v/max>.2?'#ff8a3d':'#fff59d',name=f=>{const p=f.properties||{};return p.shapeName||p.name||p.NAME_1||p.NAME_2||p.NAME||'Area'},map=L.map(item.id,{scrollWheelZoom:false}),base=tiles[state.basemap]||tiles['carto-light'];L.tileLayer(base[0],{attribution:base[1],maxZoom:19}).addTo(map);let layer=L.geoJSON(w.geojson,{style:f=>{const n=counts.get(norm(name(f)))||0;return{color:'#34444c',weight:1,fillColor:color(n),fillOpacity:.82}},onEachFeature:(f,l)=>{const n=name(f),v=counts.get(norm(n))||0;l.bindTooltip(`${esc(n)}: ${v}`,{sticky:true}).bindPopup(`<b>${esc(n)}</b><br>Value: ${v.toLocaleString()}`);l.on({mouseover:e=>e.target.setStyle({weight:3,fillOpacity:1}),mouseout:e=>layer.resetStyle(e.target)})}}).addTo(map);map.fitBounds(layer.getBounds(),{padding:[16,16]});const legend=L.control({position:'topright'});legend.onAdd=()=>{const d=L.DomUtil.create('div','legend'),steps=[0,.2,.4,.6,.8].map(x=>Math.round(max*x));d.innerHTML='<b>Value</b>'+steps.map(x=>`<span><i style="background:${color(x)}"></i>${x.toLocaleString()}${x===steps.at(-1)?'+':''}</span>`).join('');return d};legend.addTo(map)}
draw(state.snapshot);async function refresh(){try{const r=await fetch('/api/live');if(r.ok)draw(await r.json())}catch(e){}}if(state.mode==='live'){refresh();setInterval(refresh,state.refresh_minutes*60000)}
</script></body></html>'''
    return page.replace("__TITLE__", escape(title)).replace("__TITLE__", escape(title)).replace("__PRIMARY__", escape(primary)).replace("__MODE__", escape(mode.title())).replace("__PAYLOAD__", payload)


def _worker(upstream_url: str, refresh: int) -> str:
    return f'''const UPSTREAM={json.dumps(upstream_url)};export default{{async fetch(request,env){{const url=new URL(request.url);if(url.pathname==="/api/live"){{const headers={{accept:"application/json"}};if(env.UPSTREAM_API_TOKEN)headers.authorization=`Bearer ${{env.UPSTREAM_API_TOKEN}}`;const response=await fetch(UPSTREAM,{{headers,cf:{{cacheTtl:{refresh * 60},cacheEverything:true}}}});if(!response.ok)return Response.json({{error:"Live source unavailable"}},{{status:502}});return new Response(response.body,{{headers:{{"content-type":"application/json","cache-control":"public,max-age={refresh * 60}","access-control-allow-origin":"*"}}}})}}return env.ASSETS.fetch(request)}}}};'''
