"""Privacy-gated Cloudflare Pages dashboard publication bundles."""

from __future__ import annotations

from html import escape
from io import BytesIO
import json
import re
from typing import Any
from urllib.parse import urlparse
from zipfile import ZIP_DEFLATED, ZipFile


ALLOWED_WIDGETS = {"kpi", "field_kpi", "chart", "field_chart", "map", "epi_curve", "geo_map", "content"}


def publication_audit(config: Any, dashboard: dict[str, Any], mode: str, upstream_url: str = "") -> dict[str, Any]:
    if mode not in {"snapshot", "live"}: raise ValueError("Publication mode must be snapshot or live.")
    if mode == "live" and (urlparse(upstream_url).scheme != "https" or not urlparse(upstream_url).netloc):
        raise ValueError("Live publication requires an HTTPS aggregate API URL.")
    findings, sources = [], []
    for widget in dashboard.get("widgets", []):
        kind = widget.get("type")
        if kind not in ALLOWED_WIDGETS: findings.append(f"Unsupported widget type: {kind}"); continue
        dataset_name, fields = widget.get("dataset"), []
        if kind in {"field_kpi", "field_chart"}: fields = [widget.get("field")]
        elif kind == "epi_curve": fields = [widget.get("date_field"), widget.get("value_field")]
        elif kind == "geo_map": fields = [widget.get("latitude_field"), widget.get("longitude_field")]
        if dataset_name in config.datasets:
            dataset = config.datasets[dataset_name]
            protected = [name for name in fields if name and name in dataset.fields and dataset.fields[name].protected]
            if protected: findings.append(f"{widget.get('title', kind)} uses protected field(s): {', '.join(protected)}")
            sources.append({"dataset": dataset_name, "fields": [name for name in fields if name], "output": "aggregate"})
        if kind == "kpi" and widget.get("indicator") in config.indicators:
            indicator = config.indicators[widget["indicator"]]
            dataset = config.datasets[indicator.dataset]
            fields = [indicator.field, indicator.numerator, indicator.denominator, indicator.date_field, *indicator.filters]
            protected = [name for name in fields if name and name in dataset.fields and dataset.fields[name].protected]
            if protected: findings.append(f"{widget.get('title', kind)} indicator uses protected field(s): {', '.join(protected)}")
            sources.append({"dataset": indicator.dataset, "indicator": indicator.name, "output": "aggregate"})
        if kind in {"chart", "map"} and widget.get("dimension") in config.dimensions:
            dimension = config.dimensions[widget["dimension"]]; field = config.datasets[dimension.dataset].fields[dimension.field]
            if field.protected: findings.append(f"{widget.get('title', kind)} uses protected dimension field: {dimension.field}")
            sources.append({"dataset": dimension.dataset, "field": dimension.field, "output": "aggregate"})
    return {"approved": not findings, "mode": mode, "dashboard_id": dashboard.get("id") or dashboard.get("name"), "row_level_records": 0, "protected_fields": 0 if not findings else len(findings), "sources": sources, "findings": findings, "live_endpoint": upstream_url if mode == "live" else "", "notice": "Publication exports aggregate dashboard evidence only; this is a technical control, not a legal privacy certification."}


def build_bundle(dashboard: dict[str, Any], snapshot: dict[str, Any], branding: dict[str, Any], mode: str, upstream_url: str = "", refresh_minutes: int = 15) -> bytes:
    refresh = max(1, min(int(refresh_minutes), 1440))
    title = str(dashboard.get("title") or dashboard.get("label") or "Public Health Dashboard")
    payload = json.dumps({"dashboard": dashboard, "snapshot": snapshot, "mode": mode, "refresh_minutes": refresh}).replace("</", "<\\/")
    primary = branding.get("primary_color", "#087e8b")
    html = _page(title, payload, primary, mode)
    worker = _worker(upstream_url, refresh) if mode == "live" else ""
    readme = f"""# {title}\n\nGenerated by PHFrame.\n\nMode: {mode}\n\nDeploy with `npx wrangler pages deploy . --project-name YOUR_PROJECT`.\n"""
    output = BytesIO()
    with ZipFile(output, "w", ZIP_DEFLATED) as archive:
        archive.writestr("index.html", html); archive.writestr("README.md", readme)
        archive.writestr("_headers", "/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: no-referrer\n  X-Frame-Options: DENY\n")
        if worker: archive.writestr("_worker.js", worker)
    return output.getvalue()


def safe_project_name(value: str) -> str:
    clean = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")[:58]
    if not clean: raise ValueError("Cloudflare project name is required.")
    return clean


def _page(title: str, payload: str, primary: str, mode: str) -> str:
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><style>:root{{--p:{escape(primary)};--bg:#f4f7f7;--card:#fff;--text:#17313d}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--text);font:15px/1.5 system-ui}}header{{padding:2.4rem 5vw;color:#fff;background:var(--p)}}main{{max-width:1200px;margin:auto;padding:2rem}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem}}article{{padding:1.2rem;background:var(--card);border:1px solid #d5e1e3;border-radius:14px}}.value{{font-size:2.5rem;font-weight:800;color:var(--p)}}.bars i{{display:block;height:12px;margin:.4rem 0;background:var(--p);border-radius:9px}}footer{{padding:2rem;text-align:center;color:#64777e}}.status{{font-size:.8rem;opacity:.8}}</style></head><body><header><h1>{escape(title)}</h1><p class="status">{escape(mode.title())} dashboard · aggregate data only</p></header><main><div class="grid" id="dashboard"></div></main><footer>Published with PHFrame</footer><script id="ph-data" type="application/json">{payload}</script><script>const state=JSON.parse(document.querySelector('#ph-data').textContent),host=document.querySelector('#dashboard');function draw(data){{const values=data.widgets||[];host.innerHTML=values.map(w=>`<article><h2>${{esc(w.title||w.type)}}</h2>${{render(w)}}</article>`).join('')}}function esc(v){{const e=document.createElement('span');e.textContent=v??'';return e.innerHTML}}function render(w){{if(w.html)return w.html;if(w.value!==undefined)return `<div class="value">${{Number(w.value).toLocaleString()}}</div><p>${{esc(w.operation||'aggregate')}}</p>`;if(w.values){{const m=Math.max(1,...w.values.map(x=>x.count||x.value||0));return `<div class="bars">${{w.values.slice(0,20).map(x=>`<b>${{esc(x.label||x.value||x.date)}}</b><i style="width:${{Math.max(2,(x.count||x.value||0)/m*100)}}%"></i>`).join('')}}</div>`}}return '<p>No aggregate data available.</p>'}}draw(state.snapshot);async function refresh(){{try{{const r=await fetch('/api/live');if(r.ok)draw(await r.json())}}catch(e){{}}}}if(state.mode==='live'){{refresh();setInterval(refresh,state.refresh_minutes*60000)}}</script></body></html>'''


def _worker(upstream_url: str, refresh: int) -> str:
    return f'''const UPSTREAM={json.dumps(upstream_url)};export default{{async fetch(request,env){{const url=new URL(request.url);if(url.pathname==="/api/live"){{const headers={{accept:"application/json"}};if(env.UPSTREAM_API_TOKEN)headers.authorization=`Bearer ${{env.UPSTREAM_API_TOKEN}}`;const response=await fetch(UPSTREAM,{{headers,cf:{{cacheTtl:{refresh * 60},cacheEverything:true}}}});if(!response.ok)return Response.json({{error:"Live source unavailable"}},{{status:502}});return new Response(response.body,{{headers:{{"content-type":"application/json","cache-control":"public,max-age={refresh * 60}","access-control-allow-origin":"*"}}}})}}return env.ASSETS.fetch(request)}}}};'''
